{"title": ["Jurassic World: Fallen Kingdom"], "summary": ["When the island's dormant volcano begins roaring to life, Owen and Claire mount a campaign to rescue the remaining dinosaurs from this extinction-level event."], "director": ["J.A. Bayona"]}
{"title": ["A Quiet Place"], "summary": ["In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing."], "director": ["John Krasinski"]}
{"title": ["Ready Player One"], "summary": ["When the creator of a virtual reality world called the OASIS dies, he releases a video in which he challenges all OASIS users to find his Easter Egg, which will give the finder his fortune."], "director": ["Steven Spielberg"]}
{"title": ["Once Upon a Time in Hollywood"], "summary": ["A TV actor and his stunt double embark on an odyssey to make a name for themselves in the film industry during the Charles Manson murders in 1969 Los Angeles."], "director": ["Quentin Tarantino"]}
{"title": ["Mandy"], "summary": ["Mandy is set in the primal wilderness of 1983 where Red Miller, a broken and haunted man hunts an unhinged religious sect who slaughtered the love of his life."], "director": ["Panos Cosmatos"]}
{"title": ["Uncle Drew"], "summary": ["After draining his life savings to enter a team in the Rucker Classic street ball tournament in Harlem, Dax (Lil Rel Howery) is dealt a series of unfortunate setbacks, including losing his ..."], "director": ["Charles Stone III"]}
{"title": ["Sanju"], "summary": ["Sanju is a biopic of the controversial life of actor"], "director": ["Rajkumar Hirani"]}
{"title": ["The Incredibles"], "summary": ["A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world."], "director": ["Brad Bird"]}
{"title": ["Solo: A Star Wars Story"], "summary": ["During an adventure into the criminal underworld, Han Solo meets his future copilot Chewbacca and encounters Lando Calrissian years before joining the Rebellion."], "director": ["Ron Howard"]}
{"title": ["Tag"], "summary": ["A small group of former classmates organize an elaborate, annual game of tag that requires some to travel all over the country."], "director": ["Jeff Tomsic"]}
{"title": ["Hereditary"], "summary": ["After the family matriarch passes away, a grieving family is haunted by tragic and disturbing occurrences, and begin to unravel dark secrets."], "director": ["Ari Aster"]}
{"title": ["Blockers"], "summary": ["Three parents try to stop their daughters from losing their virginity on prom night."], "director": ["Kay Cannon"]}
{"title": ["Deadpool 2"], "summary": ["Foul-mouthed mutant mercenary Wade Wilson (AKA. Deadpool), brings together a team of fellow mutant rogues to protect a young boy with supernatural abilities from the brutal, time-traveling cyborg, Cable."], "director": ["David Leitch"]}
{"title": ["Ant-Man and the Wasp"], "summary": ["As Scott Lang balances being both a Super Hero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past."], "director": ["Peyton Reed"]}
{"title": ["Ocean's Eight"], "summary": ["Debbie Ocean gathers an all-female crew to attempt an impossible heist at New York City's yearly Met Gala."], "director": ["Gary Ross"]}
{"title": ["Christopher Robin"], "summary": ["A working-class family man, Christopher Robin, encounters his childhood friend Winnie-the-Pooh, who helps him to rediscover the joys of life."], "director": ["Marc Forster"]}
{"title": ["Dunkirk"], "summary": ["Allied soldiers from Belgium, the British Empire and France are surrounded by the German Army, and evacuated during a fierce battle in World War II."], "director": ["Christopher Nolan"]}
{"title": ["It: Chapter Two"], "summary": ["27 years later, the Losers Club have grown up and moved away, until a devastating phone call brings them back."], "director": ["Andy Muschietti"]}
{"title": ["Lady Bird"], "summary": ["In 2002, an artistically inclined seventeen-year-old girl comes of age in Sacramento, California."], "director": ["Greta Gerwig"]}
{"title": ["The Catcher Was a Spy"], "summary": ["A major league baseball player, Moe Berg, lives a double life working for the Office of Strategic Services."], "director": ["Ben Lewin"]}
{"title": ["Midnight Sun"], "summary": ["A 17-year-old girl suffers from a condition that prevents her from being out in the sunlight."], "director": ["Scott Speer"]}
{"title": ["Ant-Man"], "summary": ["Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world."], "director": ["Peyton Reed"]}
{"title": ["The King of Thieves"], "summary": ["A crew of retired crooks pull off a major heist in London's jewelry district."], "director": ["James Marsh"]}
{"title": ["Avengers: Infinity War"], "summary": ["The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe."], "director": ["Anthony Russo"]}
{"title": ["Hotel Artemis"], "summary": ["Set in riot-torn, near-future Los Angeles, 'Hotel Artemis' follows the Nurse, who runs a secret, members-only emergency room for criminals."], "director": ["Drew Pearce"]}
{"title": ["Unsane"], "summary": ["A young woman is involuntarily committed to a mental institution, where she is confronted by her greatest fear--but is it real or a product of her delusion?"], "director": ["Steven Soderbergh"]}
{"title": ["Won't You Be My Neighbor?"], "summary": ["An exploration of the life, lessons, and legacy of iconic children's television host,"], "director": ["Morgan Neville"]}
{"title": ["SuperFly"], "summary": ["With retirement on his mind, a successful young drug dealer sets up one last big job, while dealing with trigger-happy colleagues and the police."], "director": ["Director X."]}
{"title": ["Truth or Dare"], "summary": ["A harmless game of Truth or Dare among friends turns deadly when someone -- or something -- begins to punish those who tell a lie or refuse the dare."], "director": ["Jeff Wadlow"]}
{"title": ["Justice League"], "summary": ["Fueled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne enlists the help of his newfound ally, Diana Prince, to face an even greater enemy."], "director": ["Zack Snyder"]}
{"title": ["Halloween"], "summary": ["Laurie Strode comes to her final confrontation with Michael Myers, the masked figure who has haunted her since she narrowly escaped his killing spree on Halloween night four decades ago."], "director": ["David Gordon Green"]}
{"title": ["Captain Marvel"], "summary": ["Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races."], "director": ["Anna Boden"]}
{"title": ["Guardians of the Galaxy"], "summary": ["A group of intergalactic criminals are forced to work together to stop a fanatical warrior from taking control of the universe."], "director": ["James Gunn"]}
{"title": ["A Wrinkle in Time"], "summary": ["After the disappearance of her scientist father, three peculiar beings send Meg, her brother, and her friend to space in order to find him."], "director": ["Ava DuVernay"]}
{"title": ["Skyscraper"], "summary": ["FBI Hostage Rescue Team leader and U.S. war veteran Will Sawyer now assesses security for skyscrapers. On assignment in Hong Kong he finds the tallest, safest building in the world suddenly..."], "director": ["Rawson Marshall Thurber"]}
{"title": ["The Shape of Water"], "summary": ["At a top secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity."], "director": ["Guillermo del Toro"]}
{"title": ["X-Men: Dark Phoenix"], "summary": ["Jean Grey begins to develop incredible powers that corrupt and turn her into a Dark Phoenix. Now the X-Men will have to decide if the life of a team member is worth more than all the people living in the world."], "director": ["Simon Kinberg"]}
{"title": ["Book Club"], "summary": ["Four lifelong friends have their lives forever changed after reading 50 Shades of Grey in their monthly book club."], "director": ["Bill Holderman"]}
{"title": ["Spider-Man: Homecoming"], "summary": ["Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City."], "director": ["Jon Watts"]}
{"title": ["Baywatch"], "summary": ["Devoted lifeguard Mitch Buchannon butts heads with a brash new recruit, as they uncover a criminal plot that threatens the future of the bay."], "director": ["Seth Gordon"]}
{"title": ["Dark River"], "summary": ["Following the death of her father, Alice (Ruth Wilson) returns to her home village for the first time in 15 years, to claim the tenancy to the family farm she believes is rightfully hers."], "director": ["Clio Barnard"]}
{"title": ["The Endless"], "summary": [""], "director": ["Justin Benson"]}
{"title": ["Den of Thieves"], "summary": [""], "director": ["Christian Gudegast"]}
{"title": ["Death Wish"], "summary": [""], "director": ["Eli Roth"]}
{"title": ["Transformers: The Last Knight"], "summary": [""], "director": ["Michael Bay"]}
{"title": ["The Equalizer 2"], "summary": ["Robert McCall serves an unflinching justice for the exploited and oppressed, but how far will he go when that is someone he loves?"], "director": ["Antoine Fuqua"]}
{"title": ["Beirut"], "summary": ["Caught in the crossfires of civil war, CIA operatives must send a former U.S. diplomat to negotiate for the life of a friend he left behind."], "director": ["Brad Anderson"]}
{"title": ["Blaze"], "summary": ["The life of musician Blaze Foley."], "director": ["Ethan Hawke"]}
{"title": ["The Meg"], "summary": ["After escaping an attack by what he claims was a 70-foot shark, Jonas Taylor must confront his fears to save those trapped in a sunken submersible."], "director": ["Jon Turteltaub"]}
{"title": ["Juliet, Naked"], "summary": ["Juliet, Naked is the story of Annie (the long-suffering girlfriend of Duncan) and her unlikely transatlantic romance with once revered, now faded, singer-songwriter, Tucker Crowe, who also happens to be the subject of Duncan's musical obsession."], "director": ["Jesse Peretz"]}
{"title": ["Jumanji: Welcome to the Jungle"], "summary": ["Four teenagers are sucked into a magical video game, and the only way they can escape is to work together to finish the game."], "director": ["Jake Kasdan"]}
{"title": ["Aquaman"], "summary": ["Arthur Curry learns that he is the heir to the underwater kingdom of Atlantis, and must step forward to lead his people and to be a hero to the world."], "director": ["James Wan"]}
{"title": ["Incident in a Ghost Land"], "summary": ["The story follows a mother of two who inherits a home from her aunt. On the first night in the new home, she is confronted with murderous intruders and fights for her daughters' lives. ..."], "director": ["Pascal Laugier"]}
{"title": ["Mile 22"], "summary": ["An elite American intelligence officer, aided by a top-secret tactical command unit, tries to smuggle a mysterious police officer with sensitive information out of the country."], "director": ["Peter Berg"]}
{"title": ["Distorted"], "summary": ["A 32-year-old woman suffering from bipolar disorder comes to suspect the proprietor of the state-of-the-art ''smart apartment'' she and her husband just moved into is using the building's ..."], "director": ["Rob W. King"]}
{"title": ["The Domestics"], "summary": ["In a terrifying post-apocalyptic world inhabited by gangs divided into deadly factions, a husband and wife race desperately across the countryside in search of safety and must work together as they are pushed to the breaking point in order to survive."], "director": ["Mike P. Nelson"]}
{"title": ["Coco"], "summary": ["Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer."], "director": ["Lee Unkrich"]}
{"title": ["Brain on Fire"], "summary": ["A young, capable professional cannot explain her newly erratic behavior."], "director": ["Gerard Barrett"]}
{"title": ["Tau"], "summary": ["A woman is held captive in a futuristic smart house and hopes to escape by breaking into the computer programs that control the house."], "director": ["Federico D'Alessandro"]}
{"title": ["Glass"], "summary": ["Security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has 24 personalities."], "director": ["M. Night Shyamalan"]}
{"title": ["The Hate U Give"], "summary": ["Starr witnesses the fatal shooting of her childhood best friend Khalil at the hands of a police officer. Now, facing pressures from all sides of the community, Starr must find her voice and stand up for what's right."], "director": ["George Tillman Jr."]}
{"title": ["Star Wars: The Last Jedi"], "summary": ["Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares for battle with the First Order."], "director": ["Rian Johnson"]}
{"title": ["Mission: Impossible - Fallout"], "summary": ["Ethan Hunt and his IMF team, along with some familiar allies, race against time after a mission gone wrong."], "director": ["Christopher McQuarrie"]}
{"title": ["Annihilation"], "summary": ["A biologist signs up for a dangerous, secret expedition into a mysterious zone where the laws of nature don't apply."], "director": ["Alex Garland"]}
{"title": ["Upgrade"], "summary": ["Set in the near-future, technology controls nearly all aspects of life. But when Grey, a self-identified technophobe, has his world turned upside down, his only hope for revenge is an experimental computer chip implant called Stem."], "director": ["Leigh Whannell"]}
{"title": ["A Vingan\u00e7a Perfeita"], "summary": ["In the dark heart of a sprawling, anonymous city, TERMINAL follows the twisting tales of two assassins carrying out a sinister mission, a teacher battling a fatal illness, an enigmatic ..."], "director": ["Vaughn Stein"]}
{"title": ["It"], "summary": [""], "director": ["Andy Muschietti"]}
{"title": ["The House with a Clock in Its Walls"], "summary": ["A young orphan named Lewis Barnavelt aids his magical uncle in locating a clock with the power to bring about the end of the world."], "director": ["Eli Roth"]}
{"title": ["Game Night"], "summary": ["A group of friends who meet regularly for game nights find themselves entangled in a real-life mystery when the shady brother of one of them is seemingly kidnapped by dangerous gangsters."], "director": ["John Francis Daley"]}
{"title": ["The First Purge"], "summary": ["The film will be a prequel that will focus on the events that lead up to the very first Purge event."], "director": ["Gerard McMurray"]}
{"title": ["Hotel Transylvania 3: Summer Vacation"], "summary": ["Mavis surprises Dracula with a family voyage on a luxury Monster Cruise Ship so he can take a vacation from providing everyone else's vacation at the hotel. The rest of Drac's Pack cannot ..."], "director": ["Genndy Tartakovsky"]}
{"title": ["Blade Runner 2049"], "summary": ["A young blade runner's discovery of a long-buried secret leads him to track down former blade runner Rick Deckard, who's been missing for thirty years."], "director": ["Denis Villeneuve"]}
{"title": ["Red Sparrow"], "summary": ["Ballerina Dominika Egorova is recruited to 'Sparrow School,' a Russian intelligence service where she is forced to use her body as a weapon. Her first mission, targeting a C.I.A. agent, threatens to unravel the security of both nations."], "director": ["Francis Lawrence"]}
{"title": ["Welcome to Marwen"], "summary": ["A victim of a brutal attack finds a unique and beautiful therapeutic outlet to help him through his recovery process."], "director": ["Robert Zemeckis"]}
{"title": ["Love, Simon"], "summary": ["Simon Spier keeps a huge secret from his family, his friends, and all of his classmates: he's gay. When that secret is threatened, Simon must face everyone and come to terms with his identity."], "director": ["Greg Berlanti"]}
{"title": ["Ilha dos Cachorros"], "summary": ["Set in Japan, Isle of Dogs follows a boy's odyssey in search of his lost dog."], "director": ["Wes Anderson"]}
{"title": ["Pacific Rim: Uprising"], "summary": ["Jake Pentecost, son of Stacker Pentecost, reunites with Mako Mori to lead a new generation of Jaeger pilots, including rival Lambert and 15-year-old hacker Amara, against a new Kaiju threat."], "director": ["Steven S. DeKnight"]}
{"title": ["Life of the Party"], "summary": ["After her husband abruptly asks for a divorce, a middle-aged mother returns to college in order to complete her degree."], "director": ["Ben Falcone"]}
{"title": ["The Kissing Booth"], "summary": ["A high school student is forced to confront her secret crush at a kissing booth."], "director": ["Vince Marcello"]}
{"title": ["Adrift"], "summary": ["A true story of survival, as a young couple's chance encounter leads them first to love, and then on the adventure of a lifetime as they face one of the most catastrophic hurricanes in recorded history."], "director": ["Baltasar Korm\u00e1kur"]}
{"title": ["Creed II"], "summary": ["Under the tutelage of Rocky Balboa, newly crowned light heavyweight champion Adonis Creed faces off against Viktor Drago, the son of Ivan Drago."], "director": ["Steven Caple Jr."]}
{"title": ["How It Ends"], "summary": ["A desperate father tries to return home to his pregnant wife after a mysterious apocalyptic event turns everything to chaos."], "director": ["David M. Rosenthal"]}
{"title": ["Assassination Nation"], "summary": ["This is a thousand percent a true story about how the quiet, all-American town of Salem absolutely lost its mind."], "director": ["Sam Levinson"]}
{"title": ["Set It Up"], "summary": ["Two corporate executive assistants hatch a plan to match-make their two bosses."], "director": ["Claire Scanlon"]}
{"title": ["Kingsman: The Golden Circle"], "summary": ["When their headquarters are destroyed and the world is held hostage, the Kingsman's journey leads them to the discovery of an allied spy organization in the US. These two elite secret organizations must band together to defeat a common enemy."], "director": ["Matthew Vaughn"]}
{"title": ["Jurassic Park"], "summary": ["During a preview tour, a theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run amok."], "director": ["Steven Spielberg"]}
{"title": ["Thor: Ragnarok"], "summary": ["Thor is imprisoned on the planet Sakaar, and must race against time to return to Asgard and stop Ragnar\u00f6k, the destruction of his world, at the hands of the powerful and ruthless villain Hela."], "director": ["Taika Waititi"]}
{"title": ["The Greatest Showman"], "summary": ["Celebrates the birth of show business, and tells of a visionary who rose from nothing to create a spectacle that became a worldwide sensation."], "director": ["Michael Gracey"]}
{"title": ["Beautiful Boy"], "summary": [""], "director": ["Felix Van Groeningen"]}
{"title": ["Sicario"], "summary": [""], "director": ["Denis Villeneuve"]}
{"title": ["Jurassic World"], "summary": ["A new theme park, built on the original site of Jurassic Park, creates a genetically modified hybrid dinosaur, which escapes containment and goes on a killing spree."], "director": ["Colin Trevorrow"]}
{"title": ["Rampage"], "summary": ["When three different animals become infected with a dangerous pathogen, a primatologist and a geneticist team up to stop them from destroying Chicago."], "director": ["Brad Peyton"]}
{"title": ["Gotti"], "summary": ["The story of crime boss John Gotti and his son."], "director": ["Kevin Connolly"]}
{"title": ["Mamma Mia! Here We Go Again"], "summary": ["In this sequel to Mamma Mia!, Sophie learns about her mother's past while pregnant herself."], "director": ["Ol Parker"]}
{"title": ["Tomb Raider"], "summary": [""], "director": ["Roar Uthaug"]}
{"title": ["Black Panther"], "summary": ["T'Challa, the King of Wakanda, rises to the throne in the isolated, technologically advanced African nation, but his claim is challenged by a vengeful outsider who was a childhood victim of T'Challa's father's mistake."], "director": ["Ryan Coogler"]}
{"title": ["Sicario 2: Soldado"], "summary": ["The drug war on the U.S.-Mexico border has escalated as the cartels have begun trafficking terrorists across the US border. To fight the war, federal agent Matt Graver re-teams with the mercurial Alejandro."], "director": ["Stefano Sollima"]}
{"title": ["The Predator"], "summary": ["When a young boy accidentally triggers the universe's most lethal hunters return to Earth, only a ragtag crew of ex-soldiers and a disgruntled science teacher can prevent the end of the human race."], "director": ["Shane Black"]}
{"title": ["Escape Plan 2: Hades"], "summary": ["Years after he fought his way out of an inescapable prison, Ray Breslin has organized a new top-notch security force. But when one of his team members goes missing, Breslin must return to the hell he once escaped from."], "director": ["Steven C. Miller"]}
{"title": ["Incredibles 2"], "summary": ["Bob Parr (Mr. Incredible) is left to care for the kids while Helen (Elastigirl) is out saving the world."], "director": ["Brad Bird"]}
